name: build

# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# https://docs.github.com/en/actions/reference
# https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
# https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts
# https://github.github.io/actions-cheat-sheet/actions-cheat-sheet.pdf
# https://github.com/actions/checkout
# https://github.com/actions/cache
#
# TODO:
#   - better caching: https://stackoverflow.com/questions/59269850/caching-apt-packages-in-github-actions-workflow
#   - Create a test result branch: `REPO/test-results`.
#   - Commit test outputs to the test result branch.
# https://stackoverflow.com/questions/57921401/push-to-origin-from-github-action/58393457#58393457


concurrency:
  group: build
  cancel-in-progress: true

on:
  # pull_request:
  #   types: [ assigned, opened, synchronize, reopened ]
  push:
    branches:
      - test-github-actions

jobs:
  noskipci:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "not contains '[skip ci]'"
  build:
    runs-on: ${{ matrix.buildHost }}
    needs: noskipci
    strategy:
      fail-fast: false
      matrix:
        buildHost:
          - ubuntu-latest
        platform:
          - genode-native
        nim:
          - stable
    steps:
      - uses: actions/checkout@v2
      - id: run-genode
        run: |
          {
            curl -L https://genode.org/files/sculpt/sculpt-22-04.img -o skulpt.img &
            fetch_jobs=$!
            sudo apt-get install qemu-kvm qemu libvirt-bin &
            fetch_jobs="$fetch_jobs $!"
            wait $fetch_jobs
          }
          qemu-system-x86_64 -display sdl -cpu core2duo -machine q35 -m 1024 -drive format=raw,file=sculpt.img
